### ISSUE TITLE
Question: High-level rules inside Struct

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-types#117]
Assume I have `Customer` model:

```ruby
    class Customer < Dry::Types::Struct
      attribute :date_of_birth, Types::Nil | Types::Date
      attribute :ssn, Types::Nil | Types::SSN
    end
```

Invariant I have in my model is that either date_of_birth or ssn should be setup. How can I specify that invariant? `dry-validations` has cool way to setup it for schema (http://dry-rb.org/gems/dry-validation/high-level-rules/), can I use something similar for my entity? 

More common question is should I put validation rules inside struct initialization? As for me, that's only way I can prevent objects with illegal states. Actually, there would be great to have opportunity to set some validation schema for struct - that would avoid code duplication. 

Of course, client can validation hash with schema before object creation, but I'd not trust to client code, and that leaves possibility to create object with illegal state, if client forgot to validate before.

Thanks

**Comment by flash-gordon** [comment]
Hi, @Kukunin. 

Dry::Struct and Dry::Types are not intended to perform high-level checks for you, because they're about, well, types. Any complex validation logic should be placed outside of their definition. If you're worry about consistency of your data, I'd recommend you to use database constraints—this way no one will ever be able insert invalid records in the table. You can also define a constructor for your struct and perform some validation there (don't forget to call `super` first). I use the later approach in one of my types where I want to be absolutely sure I don't have an invalid value (it's time span, runtime only value, ie no persistence).

**Comment by Kukunin** [comment]
Good answer. Thanks!

While I agree with you about Dry::Types, it may be possible feature for Dry::Struct, because latter is all about structs =)
