### ISSUE TITLE
More complex validations

### ISSUE THREAD

**Issue by Incanus3** [dry-rb/dry-types#177]
I've read in http://dry-rb.org/gems/dry-types/constraints/ you can add validations to Dry::Types using the `.constrained` method and that 'Under the hood it uses dry-logic and all of its predicates are supported'. What I'm not sure about is, how do I pass more complex constraints to this method. My use case here (and I don't think I'm alone) is an optional dry-struct attribute like this

```ruby
class BillHeader < Dry::Struct
  constructor_type :schema

  attribute :type, Types::Strict::String.optional.constrained(size: 1)
end
```

This works correctly if I provide the `type` attribute. The problem appears when I do not. In that case I get `NoMethodError: undefined method 'size' for nil:NilClass`. What I'd like to do is something like

```ruby
attribute :type, Types::Strict::String.optional.constrained { filled? > size?(1) }
```

Is there an easy way to do this, or do I have to define a schema for the whole constructor `**args` hash and override the constructor, thus greatly decreasing the dry-ness of the definition?

**Comment by flash-gordon** [comment]
@Incanus3 it must be `Types::Strict::String.constrained(size: 1).optional` 
`.optional` returns you a `Sum` type which has left (nil type) and right (string type) parts, but your constraint is applicable only for strings, that's why `.constrained` must be called on `Types::Strict::String`.

We won't add a DSL for validations to dry-types or dry-structs because constraints _are not_ validations and you need to check your business/domain rules outside of structs.

**Comment by Incanus3** [comment]
Ok, this makes sense, thank you for the clarification. Concerning your statement that "constraints are not validations", is there some design document clarifying the distinction?

**Comment by flash-gordon** [comment]
Thoughtbots wrote an article about exactly this recently https://robots.thoughtbot.com/validation-database-constraint-or-both. Treat a struct as a table definition.

**Comment by solnic** [comment]
> "constraints are not validations", is there some design document clarifying the distinction?

We should probably explain this better in dry-types/struct docs. The difference between type/struct constraints and validations is that constraints are meant to raise exceptions, whereas validations are not, because when you validate data you assume that the input may or may not be valid, and in both cases it's OK and your system should handle it gracefully. Now, with constraints, if one of your struct raises an exception due to constraint violation then it means you've got a bug in your system that you want to fix, because for some reason your system was in an invalid state.

**Comment by Incanus3** [comment]
OK, this makes perfect sense and the article is very nicely written. The use-case differences are clear from the explanation, what I don't get in the context of dry-struct and dry-types is, why should the constraints-related tools be less powerful that the validations-related ones? What if some more complex rule _does_ make sense in all contexts (different sources the data is coming from) and it _is_ a bug that you should be notified about? Why would you want to intentionally reduce their power by deciding not to support more complex ones even though you already have a very nice tool for their definition and checking? I can't of course estimate how complex it would be to implement e.g. the block support for .constrained I've suggested, so if it's too hard and not worth the cost, I'd get that, but I don't understand the deliberate decision not to.

**Comment by solnic** [comment]
> Why would you want to intentionally reduce their power by deciding not to support more complex ones even though you already have a very nice tool for their definition and checking?

Because it's not needed. Structs and individual types that they may use don't need complex constraints. Intentional usage of dry-struct includes things like data structs created from data that is expected to be valid. This means it was already persisted in a db, or came from an external system as JSON that went through coercion/validation layer already. If we add similar API as we have in dry-validation then it will suggest that structs can be used for validation, which is literally the opposite of how dry-struct should be used.

Another thing is that a type represents a single concept and if multiple types are allowed, then a sum type should be used. That's why we don't allow constraints with disjunctions so that you can't do `constrained { array? | str? }` because what you want is `Types::Strict::Array | Types::Strict::String`.

**Comment by Incanus3** [comment]
OK, if these are the only situations dry-structs should be used, then this makes sense. In my case, I'm using dry-struct for creating PORO entities, which are then serialized and used to interact with a backend API (both reads and writes). But since I want to be able to swap the persistence backend in the future (or at least treat it as an implementation detail), the client (including the dry-struct entities) on which the rest of the client-side code is built _is_ the persistent layer for me. Thus I want to have sanity checking on this level ensuring the data integrity (i.e. constraints, not validations). Now imagine there is a model storing e.g. clients' insurance numbers, for which there are certain rules (they are divisible by 11, etc.) and I want to ensure this is true everywhere, no matter where the data comes from - I don't want any code to be able to create the Client entity with an insurance number not satisfying these properties. Now, there may of course be validations ensuring this for various data sources as well, to show proper error messages to the users etc., but that doesn't mean there shouldn't be a constraint for this. Hence again, I'm not convinced the constraints should be less powerful than the validations. Or is this a use-case I shouldn't use dry-struct for?

Please don't get me wrong, I'm not arguing for the sake of the argument, I just want to grasp the reasoning behind this and make sure I'm using dry-struct right.

I completely agree with the latter part of your comment concerning the disjunction rules.

**Comment by flash-gordon** [comment]
@Incanus3 you can build your own data type for this
```ruby
InsuranceNumber = Dry::Types['strict.int'].constructor { |v| v.tap { 
                    raise TypeError, 'invalid insurance number' if v % 11 != 0
                  } }
```
then you'll be able to use it throughout your application, including structs
```ruby
InsuranceNumber[11] # => 11
InsuranceNumber[12] # => TypeError: invalid insurance number

class Foo < Dry::Struct
  attribute :in, InsuranceNumber
end

Foo.new(in: 11) # => #<Foo in=11>
Foo.new(in: 12) # => TypeError: invalid insurance number
```

**Comment by Incanus3** [comment]
Yes, I can. I just think I should be able to achieve this using constraint, since this is technically a constraint. And I still think this is a valid argument for having constraints as powerful as validations, because even though they are not the same, they still can and sometimes have to be more complex.

**Comment by solnic** [comment]
We can add support for more complex constraints once somebody has a real-world use case :)

**Comment by replaid** [comment]
I am using dry-struct to model/Anti-Corruption Layerize a legacy JSON API thing that has both integers and strings as IDs. I want to constrain it so that `"123"` is invalid but `"my_id"` and `123` are valid. Do I win the use-case hunt?

**Comment by solnic** [comment]
@replaid you can achieve this via `Types::Strict::String | Types::Strict::Integer`

**Comment by replaid** [comment]
@solnic I already have that. For this situation `"123"` is invalid and means something broke.

**Comment by solnic** [comment]
@replaid then use the format constraint with a regexp
