### ISSUE TITLE
Support fine-grained configuration of hash schema behaviour

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-types#194]
In a dry-web app, we wanted to use a hash schema on a rom-rb relation schema to both symbolize incoming keys, filter out unknown keys, but also raise if keys were missing. The thinking behind this was that we could use the schema type as a protection to ensure we only push valid data into this part of our database.

This sort of behaviour isn't possible with any of the current hash schema types.

I think it'd be great if we could allow fine-grained configuration over each of the behavioural elements of hash schemas. e.g.

- value with invalid type? raise/pass value to output
- omitted key? populate with default/raise/produce output without key
- key not specified in schema? omit/raise
- value is nil? replace with default/pass nil value through
- string keys? symbolize/pass string keys through

Being able to control each of these things would allow hash schemas to be used in many currently unforeseen scenarios. We should probably continue to offer a few "standard" configurations (maybe the ones we have now? or maybe some small adjustments to those?), and we should probably make it easy for an app developer to take their preferred configuration and "capture" it somehow so it can be easily used across multiple hash schemas in that app.

@solnic I know you were planning to file an issue for this, but I thought I'd just get things started :)

**Comment by rushilagr** [comment]
Another use case for fine grained control:

An HTTP API returns a hash representing various attributes of an object. I want to have certain constraints over some of the keys, but I want the non-mentioned keys to be passed through cleanly. This is because the incoming data in is dynamic and I cannot fully predict all keys.

Currently, all of the hash schema configurations stop non-explicitly mentioned keys from passing through.

**Comment by rushilagr** [comment]
Additionally,
using dry-validation's Schema type (with default configuration) allows non-mentioned keys to pass through. Don't know if that is by intent or chance.

**Comment by JDutil** [comment]
My use case for this is very similar to the ones mentioned above. Except rather than an API interaction I'm interacting with DynamoDB through rom-rb relations.  My issue is that DynamoDB doesn't have a set schema, and so it just saves whatever hash is provided for the record to the DB.  So if an attribute doesn't exist for the record yet when it's created/saved no key/value pair is saved in the DB record.  When I try to load that record I receive MissingKeyError, and so I currently have to work around this by saving all the key/value pairs not in use yet to the database which wastes resources as I'm saving a bunch of keys with null values. 

I'm also having issues with incoming hashes using string keys, but other aspects of rom using symbolized keys.  I haven't worked out a workaround for that yet, and so these would certainly be some welcome improvements. I seem to keep working around issues rather than following the rom conventions unfortunately, which may cause us not to pursue using rom anymore until we have more elegant solutions to these problems. 

Looking forward to v1 :)

**Comment by solnic** [comment]
@JDutil FYI the work on this has been started in #230

**Comment by fledman** [comment]
@solnic @flash-gordon 
can you give a quick summary of what your plan is now that #211 and #230 are merged?
e.g. what (if anything) do you still want to get done before cutting the next release?

**Comment by flash-gordon** [comment]
@fledman we need to come up with a new API for schemas based on the new internals, this is a pretty straight-forward task and I'll do it during this week. After that, we'll go through the backlog and should be ready for 1.0.beta (no kidding!).

**Comment by flash-gordon** [comment]
Looks like we're all set in https://github.com/dry-rb/dry-types/pull/231
