### ISSUE TITLE
Inconsistent coercion behavior for nil values

### ISSUE THREAD

**Issue by contentfree** [dry-rb/dry-types#207]
Given:

```ruby
    class TestContract < ::Reform::Form
      include ::Reform::Form::Coercion
      property :my_decimal, type: Types::Form::Decimal, default: 0.0
      validation do
        required(:my_decimal).filled(:decimal?)
      end
    end

    contract = TestContract.new(OpenStruct.new(my_decimal: nil))
```

My expectation is that `contract.validate(my_decimal: nil)` should be true due to coercing nil to decimal. However, the value remains nil. 

This is inconsistent: If I had given Types::Coercible::String as the type, the nil value is coerced to an empty string.

More information at https://gitter.im/trailblazer/chat?at=59519caf703e565c33489421

**Comment by konung** [comment]
To add to @contentfree bugs report, since we discussed this on Trailblazer gitter channel

- default only gets activated if nothing is passed to the property ( as expected IMHO)
- default should also get activated, if coercion results in nil or '' value, if default is set, otherwise nil ( what do you think?)
- type: Types::Form::Decimal, default: 0.0 doesn’t coerce nil to 0.0 as expected. Form is a built on top of Coercible I think - so it should at least match that behavior
- type: Types::Coercible::Decimal, default: 0.0, actually coerses ‘’ (empty string) to 0.0, but not the nil - which is inconsistent

input value of all of these examples was nil or '' (empty_string)

**Comment by fran-worley** [comment]
To clarify, default as referenced in Reform (and the example above) is not handled by dry-types. Rather it is handed by the Default module in [Disposable](https://github.com/apotonick/disposable/blob/v0.4.3/lib/disposable/twin/default.rb)

**Comment by flash-gordon** [comment]
I checked it on master and it works fine, the result is `0.0`. I guess it's related to another problem with decimals I came across yesterday.

```ruby
[7] pry(main)> contract = TestContract.new(OpenStruct.new(my_decimal: nil)).my_decimal
=> 0.0
```
