### ISSUE TITLE
Coercion - compact arrays?

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-types#208]
It's possible I've missed something obvious but I don't seem to be able to strip nil values out of my arrays.

Say I use this Type definition
```ruby
Types::Form::Array.of(Types::Form::Nil | Types::Form::Int)
```

With a value of `[""]` it is coerced to `[nil]` which makes sense, but isn't terribly helpful when `[""]` is essentially an empty array.

This seems like a common use case, particularly in Rails where checkboxes and multi selects can return these sorts of values to represent nil.

Could we provide an option to coerce to a compact array (e.g. strip nils?)

**Comment by flash-gordon** [comment]
A more "right" way of doing this is to add a different array type which assumes member types return arrays rather than values. After mapping through the input it concatenates the result.
Example:
```ruby
member = Types::Form::Int.optional.constructor { |v| v.nil? ? EMPTY_ARRAY : [v] }
member.("foo") # => ["foo"]
member.("") # => []
Types::FlatArray.of(member).(["", "bar"]) # => ["bar"]
Types::FlatArray.of(member).(["foo", "bar"]) # => ["foo", "bar"]
```
It's a more general solution since it allows to have "growable" arrays, think if member type returns an array of more than one element, this is just fine.

Another option, a type can return `Undefined` that we could treat as a missing value. This is a less general yet more simple solution since doesn't require adding a new type.

/cc @solnic
