### ISSUE TITLE
Coercion of integers with trailing zero - invalid value for Integer(): "09"

### ISSUE THREAD

**Issue by caspg** [dry-rb/dry-types#255]
I have an issue with  coercing strings with trailing zero. The issue is that `Integer(str)` interpreting leading zero as a octal digit.

```
2.4.1 :013 > Dry::Types['coercible.integer'].call('09')
ArgumentError: invalid value for Integer(): "09"
```

```
2.4.1 :023 > Integer('09')
ArgumentError: invalid value for Integer(): "09"
```

The solution is to specify base 10 number:

```
2.4.1 :025 > Integer('09', 10)
 => 9
```

Is it expected behaviour? Is there any way to configure `Types::Coercible::Integer` to allow parsing '08', and '09'?

**Comment by flash-gordon** [comment]
It's complicated, currently there is no way for this, we use what Ruby provides OOTB. In my opinion, the current ruby behavior is quite confusing because 

```ruby
Integer(10) #=> 10
Integer('10') #=> 10
Integer('10', 10) #=> 10
```
but 
```ruby
Integer(10, 10) #=> ArgumentError (base specified for non string value)
```

It looks like a bad design choice and it would be better to have `10` as a default base for strings but we have what we have. Alas, changing this would ruin the whole idea of `coercible` types so we can't change this.

It probably makes sense to change [`params.integer`](https://github.com/dry-rb/dry-types/blob/cb9c487509d7468d3a32f8cbed05070f71b35799/lib/dry/types/coercions/params.rb#L36) to work this way, though. @solnic wdyt?

@caspg keep in mind, you can construct the type you seek with 

```ruby
Dry::Types['integer'].constructor do |value|
  if value.is_a?(String)
    Integer(value, 10)
  else
    Integer(value)
  end
end
```

**Comment by GustavoCaso** [comment]
@flash-gordon @solnic I think actually makes sense changing `params.integer`

**Comment by dgutov** [comment]
This is leading zero, not trailing (wrong issue title makes searching for it harder).

DAE think that `Coercible::Integer` should also have this fix?
