### ISSUE TITLE
Types::Params::Bool coercion with ambiguous inputs simply returns ambiguous input

### ISSUE THREAD

**Issue by alexspark** [dry-rb/dry-types#276]
Given I have a Dry::Struct class that has a boolean attribute
When I parse parameters/form inputs for this attribute
It does not return intuitive results

```ruby
class MyAbstraction < Dry::Struct
  attribute :active, Types::Params::Boolean
end

MyAbstraction.new('active' => 2)['active']
# => 2
MyAbstraction.new('active' => 'please')['active']
# => 'please'
MyAbstraction.new('active' => nil)['active']
# => nil
```

This is unintuitive as I want this attribute to become a `TrueClass` or `FalseClass`. I think a more intuitive outcome would be that it throw an error that I cannot coerce it into a boolean. This is my Day 1 in `Dry-rb` so I have very little sense of what *should* be intuitive.

**Comment by alexspark** [comment]
As an alternative to what I'm trying to accomplish, I've set up a pipeline of Dry::Structs where I constrain the parameters strings.
```ruby
class MyAbstractionParameters < Dry::Struct
  attribute :active, Types::Strict::String.constrained(included_in: ['true', 'false'])
end

class MyAbstractionCoercion < Dry::Struct
  attribute :active, Types::Params::Bool  # there is no such thing as a Types::Coercion::Bool
end

class MyAbstraction < DryStruct
  attribute :active, Types::Strict::Bool
  
  def self.for(attributes={})
    new MyAbstractionCoercion.new(MyAbstractionParameters(attributes))
  end
end
```

**Comment by timriley** [comment]
@alexspark The issue here is that "params" types in dry-types are intended to coerce if possible, but also accept non-coercible data. Their use case is to help enable form post validations, where the non-coercible data still needs to remain in place after running through the types, so e.g. the form can be redisplayed.

Something like this would work for you:

```ruby
class Thing < Dry::Struct
  attribute :active, Types::Strict::Bool.constructor(Types::Params::Bool)
end

Thing.new(active: "1")
# => #<Thing active=true>

Thing.new(active: "0")
# => #<Thing active=false>

Thing.new(active: "nope")
# Dry::Struct::Error ([Thing.new] "nope" (String) has invalid type for :active violates constraints (type?(FalseClass, "nope") failed))
```

If your data is coming in from untrusted input (i.e. from a form post), I'd recommend you run it through a dry-validation schema first, and only initialize the structs if the data is valid, then handling the invalid data case in whichever way makes sense for your app.

Since I don't think this is an actual bug in dry-struct behaviour I'm going to close this issue. For future discussion as you learn the dry-rb gems I'd recommend you head over to https://discourse.dry-rb.org :)
