### ISSUE TITLE
Blacklist / whitelist sensitive data from SchemaError

### ISSUE THREAD

**Issue by lancecarlson** [dry-rb/dry-types#284]
I'm not sure what a good resolution for this is, but we had sensitive data that gets stored in Dry::Structs get leaked into our logs. This is because SchemaError outputs the object's entire contents into the exception when it is raised:

https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/errors.rb#L16

In order to mitigate this in our application, we overrode this method and put our blacklisting behavior inside of this new method, but I have to imagine there is a more elegant solution here. I also have to assume that there are others that will be storing sensitive information in their Dry::Structs!

Thoughts?

**Comment by flash-gordon** [comment]
I would suggest overriding `inspect` in the struct class instead. You can also build your own base class for structs and put it there, it's safe since we don't use `inspect` internally for anything else but for error messages.

Please ask questions on our forum or on the gitter chat as mentioned in our contributing guidelines https://github.com/dry-rb/dry-types/blob/master/CONTRIBUTING.md

**Comment by lancecarlson** [comment]
@flash-gordon Thank you ! Completely did not realize there was a gitter. Sorry!
