### ISSUE TITLE
Misleading name for builder `Instance`

### ISSUE THREAD

**Issue by waiting-for-dev** [dry-rb/dry-types#336]
```ruby
module Types
  include Dry.Types
end

module A
end

class B
  include A
end

B.new.instance_of?(A) #=> false
Types.Instance(A)[B.new] #= > #<B:...>
B.new.is_a?(A) #=> true
B.new.kind_of?(A) #=> true
```

Even if it is well documented, `Instance` name suggest that `#instance_of?` will be called. However, `#is_a?` is actually called, which is the same as `#kind_of?`. For this reason, I would change `Instance` for `Kind` and introduce a new `Instance` which would call `#instance_of?`.

What do you think? I can take it myself if you agree.

**Comment by flash-gordon** [comment]
I see no point in the `instance_of?` check, I never used it because it's confusing. For those rare cases where an exact match is needed `.class.equal?` is way better. However, I consider having built-in support for this check in types harmful so I'm against it. We could remove `Instance` and leave only `Strict` but since we recently released 1.0 we won't do this for the sake of backwards compatibility. I suggest that we leave it as it is for now and listen for more feedback from users. If it turns to be a regular source of confusion, we'll add a warning and deprecate `Instance`.
