### ISSUE TITLE
Types::Params::Integer fails on empty strings

### ISSUE THREAD

**Issue by CodingAnarchy** [dry-rb/dry-types#344]
Form parameters return an empty string for a `nil` integer, but dry-types `Types::Params::Integer` raises an error on this: `Dry::Types::CoercionError: invalid value for Integer(): ""`.

This should be returning `nil`, as I understand the difference between `Types::Params::Integer` and `Types::Coercible::Integer`.  I've monkey-patched the method to do so in my environment, and this is a simple change.  I can open a PR if this is desired.

**Comment by flash-gordon** [comment]
This should not. Why would an `Integer` type return `nil`?

**Comment by CodingAnarchy** [comment]
Rails parameters return an empty string for an integer data type that is not set. This is a standard case for web parameters in general.

According to the documentation, this is the entire purpose of the `params` coercion.

**Comment by flash-gordon** [comment]
Right, it used to return `nil` in 0.x series but in 1.0 integer types return integers or raise an error. If you expect `nil` as a valid input, you should you use `Types::Params::Nil | Types::Params::Integer` instead. BTW this is what dry-schema does when you use `maybe(:integer)` in a `Params` schema. Thanks for referencing the outdated docs, I'll update it later today.

**Comment by CodingAnarchy** [comment]
I don't understand why I should have to use such a union type to get the standard behavior of params.  The *defining characteristic* of parameters is that they are strings, and the empty string is `nil` (or `empty` in the case of arrays or hashes). If I wanted to force coercion to integer or raise an error, this would be *identical* to the behavior of the standard `Types::Coercible::Integer`.

This design decision makes no sense to me, and drastically lowers the utility of dry-types.

**Comment by flash-gordon** [comment]
`Coercible` and `Params` are two different sets of coercion, it's easy to see. `Coercible` mostly uses builtin `Kernel` methods whereas `Params` is more "relaxed" and targets strings passed as query params etc. This doesn't change the fact that `Params::Integer` describes the set of all possible integers which doesn't include `nil` _by definition_. Adding `nil` to the set is plain wrong, what we could do instead is assign the union type I showed to `Integer` but IMO this would be quite confusing. Fortunately, this is not needed because it's all handled by dry-schema and its macros. Are you trying to use dry-types for input validation directly? If so, why not dry-schema?

**Comment by flash-gordon** [comment]
You example with `Params::Array` is not relevant because it maps an empty string to an array, it's a valid member to the `Array` set.

**Comment by CodingAnarchy** [comment]
> Coercible and Params are two different sets of coercion, it's easy to see. Coercible mostly uses builtin Kernel methods whereas Params is more "relaxed" and targets strings passed as query params etc.

This does not seem really accurate in terms of the code that actually exists in your codebase.  In the actual codebase, it appears that `Params::Integer` is actually the stricter case - if provided a string it will force the base to decimal (which makes sense, assuming the string is an HTTP integer parameter), and otherwise it appears to use the same `Kernel#Integer` to accomplish the coercion.

> This doesn't change the fact that Params::Integer describes the set of all possible integers which doesn't include nil by definition. Adding nil to the set is plain wrong

I can see why you would handle this in the event that you are considering the result as a set defined by the value in question.  What I do not understand here is the purpose of such a strict mathematical definition of the sets, rather than the intuitive concept that a `Params` coercion will give me the same results as if I feed HTTP parameters into any other system that accepts them.

> Fortunately, this is not needed because it's all handled by dry-schema and its macros. Are you trying to use dry-types for input validation directly? If so, why not dry-schema?

`dry-schema` did not fit well with `dry-initializer` in my testing of using the two.  I did not have the need to build schemas for the options to my classes.  The easiest way to work with these cases was to perform something like this operation:

```
extend Dry::Initializer
option :foo_id, type: Types::Params::Integer, optional: true
```

**Comment by flash-gordon** [comment]
> This does not seem really accurate in terms of the code that actually exists in your codebase. In the actual codebase, it appears that Params::Integer is actually the stricter case - if provided a string it will force the base to decimal (which makes sense, assuming the string is an HTTP integer parameter), and otherwise it appears to use the same Kernel#Integer to accomplish the coercion.

I'm not talking about `Integer` exclusively, take a look at other types. For instance, `Params::Bool` has a long list of values it maps. Anyway, specific rules can be discussed and improved where needed in `Params` but `Coercible` will likely stay as it is.

> I can see why you would handle this in the event that you are considering the result as a set defined by the value in question. What I do not understand here is the purpose of such a strict mathematical definition of the sets, rather than the intuitive concept that a Params coercion will give me the same results as if I feed HTTP parameters into any other system that accepts them.

This is a common interpretation of the word "type" in the context of programming languages. From this point, I draw no disctinction between Ruby and other languages, including statically typed compiled languages like, say, Haskell or Scala. The library is called "dry-types" after all. 

> dry-schema did not fit well with dry-initializer in my testing of using the two. I did not have the need to build schemas for the options to my classes. The easiest way to work with these cases was to perform something like this operation:

Ok, presumably you don't need to worry about error messages, you can build a set of custom types with coercion rules suited to your needs. Or I could a set of `optional.params` types, we have it for strict and coercible types already and I probably should have done it earlier, will it work for you?

**Comment by CodingAnarchy** [comment]
> This is a common interpretation of the word "type" in the context of programming languages.

My issue is not so much with the understanding of the word type, but the concept that `Params::Integer` maps solely to the integer type, despite the HTTP parameter having a defined provision for "no integer at all" in its usage.

> Ok, presumably you don't need to worry about error messages, you can build a set of custom types with coercion rules suited to your needs. Or I could a set of optional.params types, we have it for strict and coercible types already and I probably should have done it earlier, will it work for you?

An `optional` case for the params types would be helpful, to be sure, though I still don't understand why that wouldn't be the standard case.

**Comment by flash-gordon** [comment]
> My issue is not so much with the understanding of the word type, but the concept that Params::Integer maps solely to the integer type, despite the HTTP parameter having a defined provision for "no integer at all" in its usage. Perhaps Params is not the correct indicator for what the coercion does?

It seems to be a matter of perspective so it's not likely we'll reach any meaningful consensus over the subject. I see your point but I don't want types to have more values than they "declare" they have. You focused on "Params", I focused on "Integer".

> An optional case for the params types would be helpful, to be sure, though I still don't understand why that wouldn't be the standard case.

Because we don't need it. dry-schema is responsible for validation and it handles it nicely. For other cases constructing custom types is rather trivial. What you suggest would ruin my expectations about types (I realize it ruins yours instead).

I'll close this issue once I add `optional`s.

**Comment by flash-gordon** [comment]
@CodingAnarchy I wanted to ask you, what would you expect from `Types::Params::Integer['foo']`, `'foo'` or an error?

**Comment by CodingAnarchy** [comment]
@flash-gordon I would expect an error from `Types::Params::Integer[‘foo’]`, as that would not be a valid HTTP parameter encoding of an integer. It is only the `empty string => nil` case that would be a valid mapping outside of strings containing decimal integers.

**Comment by solnic** [comment]
> It is only the empty string => nil case that would be a valid mapping outside of strings containing decimal integers.

What do you mean by "valid mapping"? It is only valid when **you define it to be valid** - which is exactly what dry-types (and dry-schema too) allows you to do in a very nice and explicit way.

What you propose is to make this mapping valid via `Params::Integer` which would make it impossible to define an actual integer coming from HTTP params. There **are cases** where you do not expect an empty string as an input and you DO NOT want to suddenly get `nil` back, because `nil` is ambiguous - you wouldn't know if an empty string was passed and implicitly coerced (like you suggest) to `nil`, or maybe a key was missing in the params and you got implicit `nil` back (because that's how ruby hashes work), or maybe *something else* did set it to `nil`, which can happen etc. etc.

One of the biggest goals of dry-types is to remove or at least reduce ambiguity from coercions in Ruby. The way it works in Rails and many other gems is problematic, it leads to bugs, it's slow, it's sometimes confusing due to a lot of bad assumptions (including turning empty strings to nils implicitly without anything declaring this to be OK).

The actual improvement that we definitely should do is adding `optional` params so that `Types::Params::Integer.optional` uses `Params::Nil`, which is something Nikita mentioned already in this thread.

**Comment by sadjow** [comment]
Using `Types::Params::Integer.optional` resolved my issue. The `Dry::Types` is used by `Reform` gem. My case: there is a param property that is using `Types::Params::Integer`, it was working with the previous version of `Dry::Types` when the property is nil. In case the client send `nil` in the params. Optional field.
